import Foundation

/// Energy balance math — TDEE correction, deficit classification, daily balance.
///
/// Transliteration of `mobile/src/compute/energy/energy.ts`, which is itself the
/// parity port of `app/nutrition/energy.py` (pure arithmetic, no I/O, no clock).
/// Verified case-for-case against `energy.golden.json` (1,472 cases generated by
/// executing the Python).
///
/// 1:1 name mapping (Python → Swift):
/// ```
/// trailing_tdee         -> Energy.trailingTdee
/// derive_goals          -> Energy.deriveGoals
/// energy_availability   -> Energy.energyAvailability
/// corrected_tdee        -> Energy.correctedTdee
/// classify_deficit      -> Energy.classifyDeficit
/// compute_daily_balance -> Energy.computeDailyBalance
/// ```
///
/// Parity notes that are easy to lose in translation:
/// - Python guards lean/weight with `if lean_kg`, i.e. **truthiness**: `0.0` is
///   as absent as `None`. `isTruthy` below is that check, not `!= nil`.
/// - `deficit_pct_* = ... if tdee else None` is the same truthiness on the
///   divisor, so a zero TDEE yields nil rather than a division.
/// - `round(x)` (no ndigits) returns a Python `int` and never `-0.0`;
///   `round(x, 1)` returns a float and *does* preserve `-0.0`. `pythonRound`
///   encodes both, so the ndigits argument here is load-bearing.
public nonisolated enum Energy {
    /// Python's `if value:` for an optional float — nil AND 0.0 are falsy.
    private static func isTruthy(_ value: Double?) -> Bool {
        guard let value else { return false }
        return value != 0
    }

    /// Empirical TDEE over a trailing window.
    ///
    /// - Parameters:
    ///   - trackedIntakes: kcal on tracked days only (untracked days excluded).
    ///   - wStart7d: 7-day mean weight at the window start.
    ///   - wEnd7d: 7-day mean weight at the window end. The 7-day means damp the
    ///     BIA/scale water noise measured at ±0.5 kg day-to-day.
    ///   - spanDays: days between the two weight-window midpoints.
    /// - Returns: nil below `minEmpiricalTrackedDays`, on a missing weight, or on
    ///   a non-positive span — the caller then falls back to the additive model.
    public static func trailingTdee(
        _ trackedIntakes: [Double],
        wStart7d: Double?,
        wEnd7d: Double?,
        spanDays: Int,
        config: EnergyConfig = .default
    ) -> Double? {
        guard !trackedIntakes.isEmpty,
              trackedIntakes.count >= config.minEmpiricalTrackedDays,
              let wStart7d,
              let wEnd7d,
              spanDays > 0
        else { return nil }
        let avgIntake = trackedIntakes.reduce(0, +) / Double(trackedIntakes.count)
        return pythonRound(avgIntake + (wStart7d - wEnd7d) * config.kcalPerKg / Double(spanDays), 0)
    }

    /// Daily intake + macro goals from the empirical TDEE at the target pace.
    ///
    /// Protein from lean mass, fat floored at `fatMinGPerKgBW`, carbs take the
    /// remainder (reflux-safe sources, front-loaded — user_reflux_carb_constraint).
    public static func deriveGoals(
        tdee: Double,
        leanKg: Double?,
        weightKg: Double?,
        config: EnergyConfig = .default
    ) -> DeriveGoalsResult {
        let intakeKcal = pythonRound(tdee - config.deficitTargetKcal)
        let proteinG = isTruthy(leanKg) ? pythonRound(config.proteinGPerKgFFM * leanKg!) : nil
        let fatG = isTruthy(weightKg) ? pythonRound(config.fatMinGPerKgBW * weightKg!) : nil
        let carbsG: Double? = {
            guard let proteinG, let fatG else { return nil }
            return pythonRound((intakeKcal - proteinG * 4 - fatG * 9) / 4)
        }()
        return DeriveGoalsResult(intakeKcal: intakeKcal, proteinG: proteinG, fatG: fatG, carbsG: carbsG)
    }

    /// EA = (intake − exercise energy) / FFM, kcal/kg FFM/day.
    /// Below `leaThreshold` is the LEA screening zone.
    ///
    /// Caveat: device-estimated exercise kcal is itself stimulant-inflated for
    /// this user, which biases EA DOWNWARD — a sub-threshold reading is a
    /// screening flag, not a diagnosis.
    public static func energyAvailability(
        intakeKcal: Double,
        exerciseKcal: Double,
        leanKg: Double?
    ) -> Double? {
        guard isTruthy(leanKg), let leanKg else { return nil }
        return pythonRound((intakeKcal - exerciseKcal) / leanKg, 1)
    }

    /// Corrected TDEE: anchored BMR + Garmin active calories (additive model),
    /// falling back to the legacy flat `×garminTdeeCorrection` on the raw total
    /// when active kcal is missing.
    public static func correctedTdee(
        totalKcal: Double?,
        kcalBurnedActive: Double?,
        config: EnergyConfig = .default
    ) -> Double? {
        if let kcalBurnedActive {
            return pythonRound(config.bmrAnchorKcal + kcalBurnedActive, 1)
        }
        if let totalKcal {
            return pythonRound(totalKcal * config.garminTdeeCorrection, 1)
        }
        return nil
    }

    /// Map `deficitPctCorrected` (the conservative estimate) to a label.
    /// Thresholds from docs/research/energy-balance-sport-performance.md S2.2.
    public static func classifyDeficit(
        _ deficitPct: Double?,
        config: EnergyConfig = .default
    ) -> DeficitClass? {
        guard let deficitPct else { return nil }
        if deficitPct <= 0 { return .surplus }
        if deficitPct <= config.deficitMildMaxPct { return .mild }
        if deficitPct <= config.deficitModerateMaxPct { return .moderate }
        if deficitPct <= config.deficitAggressiveMaxPct { return .aggressive }
        return .dangerous
    }

    /// Energy balance for a single day. Pure — no DB, no clock.
    ///
    /// - Parameters:
    ///   - date: ISO date string, e.g. `"2026-03-30"` (carried through verbatim).
    ///   - kcalConsumed: YAZIO intake (nil when the day was not tracked).
    ///   - totalKcal: Garmin raw TDEE (nil when there was no sync).
    ///   - mealsLogged: meals logged that day, if known.
    ///   - kcalBurnedActive: Garmin active kcal — enables the additive corrected TDEE.
    ///   - tdeeEmpirical: trailing-window empirical TDEE — when present it
    ///     REPLACES the additive model as `tdeeCorrected` (device-independent
    ///     ground truth).
    public static func computeDailyBalance(
        date: String,
        kcalConsumed: Double?,
        totalKcal: Double?,
        mealsLogged: Int? = nil,
        kcalBurnedActive: Double? = nil,
        tdeeEmpirical: Double? = nil,
        config: EnergyConfig = .default
    ) -> DailyEnergyBalance {
        guard let kcalConsumed, let totalKcal else {
            let tdeeCorrected = tdeeEmpirical ?? correctedTdee(
                totalKcal: totalKcal,
                kcalBurnedActive: kcalBurnedActive,
                config: config
            )
            return DailyEnergyBalance(
                date: date,
                kcalConsumed: kcalConsumed,
                tdeeRaw: totalKcal,
                tdeeCorrected: tdeeCorrected,
                deficitRaw: nil,
                deficitCorrected: nil,
                deficitPctRaw: nil,
                deficitPctCorrected: nil,
                deficitClass: nil,
                mealsLogged: mealsLogged
            )
        }

        let tdeeRaw = totalKcal
        // `totalKcal` is non-nil here, so `correctedTdee`'s fallback branch always
        // fires when `tdeeEmpirical` is absent — mirroring the Python, which never
        // null-checks `tdee_corrected` in this branch either.
        let tdeeCorrected = tdeeEmpirical
            ?? correctedTdee(totalKcal: tdeeRaw, kcalBurnedActive: kcalBurnedActive, config: config)!
        let kcal = kcalConsumed

        let deficitRaw = pythonRound(tdeeRaw - kcal, 1)
        let deficitCorrected = pythonRound(tdeeCorrected - kcal, 1)
        let deficitPctRaw = isTruthy(tdeeRaw) ? pythonRound(deficitRaw / tdeeRaw * 100, 1) : nil
        let deficitPctCorrected = isTruthy(tdeeCorrected)
            ? pythonRound(deficitCorrected / tdeeCorrected * 100, 1)
            : nil

        return DailyEnergyBalance(
            date: date,
            kcalConsumed: kcal,
            tdeeRaw: tdeeRaw,
            tdeeCorrected: tdeeCorrected,
            deficitRaw: deficitRaw,
            deficitCorrected: deficitCorrected,
            deficitPctRaw: deficitPctRaw,
            deficitPctCorrected: deficitPctCorrected,
            deficitClass: classifyDeficit(deficitPctCorrected, config: config),
            mealsLogged: mealsLogged
        )
    }

    /// `app/shared/trends.py::avg`: mean of the non-nil values, rounded to 1
    /// decimal; nil when nothing is left.
    private static func avg(_ values: [Double?]) -> Double? {
        let clean = values.compactMap { $0 }
        guard !clean.isEmpty else { return nil }
        return pythonRound(clean.reduce(0, +) / Double(clean.count), 1)
    }

    /// Report-level averages + the compliance gate — the pure tail of
    /// `app/nutrition/queries.py::compute_energy_balance`, reproduced so a caller
    /// holding real per-day values can derive the same report shape locally.
    ///
    /// "Compliant" days are those with a non-nil `deficitCorrected` (Python's
    /// `[d for d in days if d.deficit_corrected is not None]`).
    ///
    /// No golden covers this tail (the generator only exercises the six
    /// `energy.py` functions); it is a transliteration of
    /// `energy.ts::summarizeEnergyDays` and is not consumed until the P-compute
    /// wiring row.
    public static func summarizeEnergyDays(
        _ days: [DailyEnergyBalance],
        windowDays: Int,
        config: EnergyConfig = .default
    ) -> EnergySummary {
        let compliantDays = days.filter { $0.deficitCorrected != nil }
        let trackingDays = compliantDays.count
        let compliant = trackingDays >= config.minTrackingDays

        if compliant && !compliantDays.isEmpty {
            return EnergySummary(
                avgDeficitRaw7d: avg(compliantDays.map(\.deficitRaw)),
                avgDeficitCorrected7d: avg(compliantDays.map(\.deficitCorrected)),
                avgDeficitPct7d: avg(compliantDays.map(\.deficitPctCorrected)),
                trackingDays: trackingDays,
                compliant: compliant,
                complianceWarning: nil
            )
        }
        return EnergySummary(
            avgDeficitRaw7d: nil,
            avgDeficitCorrected7d: nil,
            avgDeficitPct7d: nil,
            trackingDays: trackingDays,
            compliant: compliant,
            complianceWarning: "Tracking compliance: \(trackingDays)/\(windowDays) days — insufficient data for reliable averages."
        )
    }
}
