import Foundation
import Testing
@testable import JICompute

/// Parity tests for the energy-balance port (`app/nutrition/energy.py`).
///
/// Fixture is generated by `HealthTraining/scripts/parity/gen_golden_energy.py`
/// — ground truth is the Python module executed by the interpreter. Never edit
/// the fixture by hand; run `HealthTraining/scripts/regen_goldens.py`.
///
/// 1,472 cases in ONE `cases` array, tagged by `fn`:
/// trailingTdee 170 · deriveGoals 430 · energyAvailability 204 ·
/// correctedTdee 304 · classifyDeficit 48 · computeDailyBalance 316.
/// Each golden case is one test case, so the count `swift test` prints IS the
/// golden count.

// MARK: - Fixture plumbing

/// Strictness helpers for the energy fixture.
///
/// `StrictCase` (GoldenLoader) only guards the TOP-level keys of a case object
/// (`fn`/`input`/`output`). The energy fixture nests its real payload one level
/// down, so every nested object re-checks its own key set here: an extra key
/// means the Swift port is behind the generator, a missing key means the
/// generator changed shape — both are errors, never a silent pass.
enum EnergyFixture {
    static let file = "energy.golden"

    enum Failure: Error, CustomStringConvertible {
        case unknownKeys(group: String, keys: [String])
        case missingKeys(group: String, keys: [String])
        case unknownFunction(String)

        var description: String {
            switch self {
            case .unknownKeys(let group, let keys):
                return "energy.golden \(group) has unknown key(s) \(keys.sorted().joined(separator: ", ")) — the Swift port is behind the generator"
            case .missingKeys(let group, let keys):
                return "energy.golden \(group) is missing key(s) \(keys.sorted().joined(separator: ", ")) — the generator changed shape"
            case .unknownFunction(let fn):
                return "energy.golden has a case for unknown function \"\(fn)\" — the Swift port is behind the generator"
            }
        }
    }

    /// The nested object's key set must equal `allowed`, exactly.
    static func check(_ container: KeyedDecodingContainer<AnyKey>, allowed: Set<String>, group: String) throws {
        let present = Set(container.allKeys.map(\.stringValue))
        let unknown = present.subtracting(allowed)
        guard unknown.isEmpty else { throw Failure.unknownKeys(group: group, keys: Array(unknown)) }
        let missing = allowed.subtracting(present)
        guard missing.isEmpty else { throw Failure.missingKeys(group: group, keys: Array(missing)) }
    }

    static func input(_ decoder: Decoder, allowed: Set<String>, group: String) throws -> KeyedDecodingContainer<AnyKey> {
        let root = try decoder.container(keyedBy: AnyKey.self)
        let input = try root.nestedContainer(keyedBy: AnyKey.self, forKey: AnyKey("input"))
        try check(input, allowed: allowed, group: "\(group).input")
        return input
    }

    static func output(_ decoder: Decoder, allowed: Set<String>, group: String) throws -> KeyedDecodingContainer<AnyKey> {
        let root = try decoder.container(keyedBy: AnyKey.self)
        let output = try root.nestedContainer(keyedBy: AnyKey.self, forKey: AnyKey("output"))
        try check(output, allowed: allowed, group: "\(group).output")
        return output
    }

    /// Scalar (or null) `output` of a case whose function returns one value.
    static func scalarOutput<T: Decodable>(_ decoder: Decoder, as type: T.Type) throws -> T? {
        let root = try decoder.container(keyedBy: AnyKey.self)
        return try root.decodeIfPresent(T.self, forKey: AnyKey("output"))
    }
}

/// IEEE-754-blind equality is not enough: `0.0 == -0.0` is true, and the
/// fixture contains a genuine `-0.0` (`deficitPctRaw` on 2026-01-05). Compare
/// bit patterns, the `Object.is` the TS oracle test uses.
private func energySame(_ got: Double?, _ want: Double?) -> Bool {
    switch (got, want) {
    case (nil, nil): return true
    case (let g?, let w?): return g.bitPattern == w.bitPattern
    default: return false
    }
}

// MARK: - Cases

struct EnergyTrailingTdeeCase: Decodable, Sendable, CustomTestStringConvertible {
    let trackedIntakes: [Double]
    let wStart7d: Double?
    let wEnd7d: Double?
    let spanDays: Int
    let expected: Double?

    init(from decoder: Decoder) throws {
        let input = try EnergyFixture.input(
            decoder,
            allowed: ["trackedIntakes", "wStart7d", "wEnd7d", "spanDays"],
            group: "trailingTdee"
        )
        trackedIntakes = try input.decode([Double].self, forKey: AnyKey("trackedIntakes"))
        wStart7d = try input.decodeIfPresent(Double.self, forKey: AnyKey("wStart7d"))
        wEnd7d = try input.decodeIfPresent(Double.self, forKey: AnyKey("wEnd7d"))
        spanDays = try input.decode(Int.self, forKey: AnyKey("spanDays"))
        expected = try EnergyFixture.scalarOutput(decoder, as: Double.self)
    }

    var testDescription: String { "trailingTdee(n=\(trackedIntakes.count), span=\(spanDays))" }
}

struct EnergyDeriveGoalsCase: Decodable, Sendable, CustomTestStringConvertible {
    let tdee: Double
    let leanKg: Double?
    let weightKg: Double?
    let intakeKcal: Double
    let proteinG: Double?
    let fatG: Double?
    let carbsG: Double?

    init(from decoder: Decoder) throws {
        let input = try EnergyFixture.input(
            decoder,
            allowed: ["tdee", "leanKg", "weightKg"],
            group: "deriveGoals"
        )
        tdee = try input.decode(Double.self, forKey: AnyKey("tdee"))
        leanKg = try input.decodeIfPresent(Double.self, forKey: AnyKey("leanKg"))
        weightKg = try input.decodeIfPresent(Double.self, forKey: AnyKey("weightKg"))

        let output = try EnergyFixture.output(
            decoder,
            allowed: ["intakeKcal", "proteinG", "fatG", "carbsG"],
            group: "deriveGoals"
        )
        intakeKcal = try output.decode(Double.self, forKey: AnyKey("intakeKcal"))
        proteinG = try output.decodeIfPresent(Double.self, forKey: AnyKey("proteinG"))
        fatG = try output.decodeIfPresent(Double.self, forKey: AnyKey("fatG"))
        carbsG = try output.decodeIfPresent(Double.self, forKey: AnyKey("carbsG"))
    }

    var testDescription: String { "deriveGoals(\(tdee), \(leanKg as Double?), \(weightKg as Double?))" }
}

struct EnergyAvailabilityCase: Decodable, Sendable, CustomTestStringConvertible {
    let intakeKcal: Double
    let exerciseKcal: Double
    let leanKg: Double?
    let expected: Double?

    init(from decoder: Decoder) throws {
        let input = try EnergyFixture.input(
            decoder,
            allowed: ["intakeKcal", "exerciseKcal", "leanKg"],
            group: "energyAvailability"
        )
        intakeKcal = try input.decode(Double.self, forKey: AnyKey("intakeKcal"))
        exerciseKcal = try input.decode(Double.self, forKey: AnyKey("exerciseKcal"))
        leanKg = try input.decodeIfPresent(Double.self, forKey: AnyKey("leanKg"))
        expected = try EnergyFixture.scalarOutput(decoder, as: Double.self)
    }

    var testDescription: String { "energyAvailability(\(intakeKcal), \(exerciseKcal), \(leanKg as Double?))" }
}

struct EnergyCorrectedTdeeCase: Decodable, Sendable, CustomTestStringConvertible {
    let totalKcal: Double?
    let kcalBurnedActive: Double?
    let expected: Double?

    init(from decoder: Decoder) throws {
        let input = try EnergyFixture.input(
            decoder,
            allowed: ["totalKcal", "kcalBurnedActive"],
            group: "correctedTdee"
        )
        totalKcal = try input.decodeIfPresent(Double.self, forKey: AnyKey("totalKcal"))
        kcalBurnedActive = try input.decodeIfPresent(Double.self, forKey: AnyKey("kcalBurnedActive"))
        expected = try EnergyFixture.scalarOutput(decoder, as: Double.self)
    }

    var testDescription: String { "correctedTdee(\(totalKcal as Double?), \(kcalBurnedActive as Double?))" }
}

struct EnergyClassifyDeficitCase: Decodable, Sendable, CustomTestStringConvertible {
    let deficitPct: Double?
    let expected: DeficitClass?

    init(from decoder: Decoder) throws {
        let input = try EnergyFixture.input(decoder, allowed: ["deficitPct"], group: "classifyDeficit")
        deficitPct = try input.decodeIfPresent(Double.self, forKey: AnyKey("deficitPct"))
        expected = try EnergyFixture.scalarOutput(decoder, as: DeficitClass.self)
    }

    var testDescription: String { "classifyDeficit(\(deficitPct as Double?))" }
}

struct EnergyDailyBalanceCase: Decodable, Sendable, CustomTestStringConvertible {
    let date: String
    let kcalConsumed: Double?
    let totalKcal: Double?
    let mealsLogged: Int?
    let kcalBurnedActive: Double?
    let tdeeEmpirical: Double?
    let expected: DailyEnergyBalance

    init(from decoder: Decoder) throws {
        let input = try EnergyFixture.input(
            decoder,
            allowed: ["date", "kcalConsumed", "totalKcal", "mealsLogged", "kcalBurnedActive", "tdeeEmpirical"],
            group: "computeDailyBalance"
        )
        date = try input.decode(String.self, forKey: AnyKey("date"))
        kcalConsumed = try input.decodeIfPresent(Double.self, forKey: AnyKey("kcalConsumed"))
        totalKcal = try input.decodeIfPresent(Double.self, forKey: AnyKey("totalKcal"))
        mealsLogged = try input.decodeIfPresent(Int.self, forKey: AnyKey("mealsLogged"))
        kcalBurnedActive = try input.decodeIfPresent(Double.self, forKey: AnyKey("kcalBurnedActive"))
        tdeeEmpirical = try input.decodeIfPresent(Double.self, forKey: AnyKey("tdeeEmpirical"))

        let output = try EnergyFixture.output(
            decoder,
            allowed: [
                "date", "kcalConsumed", "tdeeRaw", "tdeeCorrected", "deficitRaw",
                "deficitCorrected", "deficitPctRaw", "deficitPctCorrected", "deficitClass", "mealsLogged",
            ],
            group: "computeDailyBalance"
        )
        expected = DailyEnergyBalance(
            date: try output.decode(String.self, forKey: AnyKey("date")),
            kcalConsumed: try output.decodeIfPresent(Double.self, forKey: AnyKey("kcalConsumed")),
            tdeeRaw: try output.decodeIfPresent(Double.self, forKey: AnyKey("tdeeRaw")),
            tdeeCorrected: try output.decodeIfPresent(Double.self, forKey: AnyKey("tdeeCorrected")),
            deficitRaw: try output.decodeIfPresent(Double.self, forKey: AnyKey("deficitRaw")),
            deficitCorrected: try output.decodeIfPresent(Double.self, forKey: AnyKey("deficitCorrected")),
            deficitPctRaw: try output.decodeIfPresent(Double.self, forKey: AnyKey("deficitPctRaw")),
            deficitPctCorrected: try output.decodeIfPresent(Double.self, forKey: AnyKey("deficitPctCorrected")),
            deficitClass: try output.decodeIfPresent(DeficitClass.self, forKey: AnyKey("deficitClass")),
            mealsLogged: try output.decodeIfPresent(Int.self, forKey: AnyKey("mealsLogged"))
        )
    }

    var testDescription: String { "computeDailyBalance(\(date), \(kcalConsumed as Double?), \(totalKcal as Double?))" }
}

/// One heterogeneous `cases` array: every entry carries its `fn` tag and the
/// payload shape that tag implies. An unknown tag fails the load — a golden
/// file that grew a seventh function must not shrink to six silently.
struct EnergyCase: GoldenCase {
    static let allowedKeys: Set<String> = ["fn", "input", "output"]

    enum Payload: Sendable {
        case trailingTdee(EnergyTrailingTdeeCase)
        case deriveGoals(EnergyDeriveGoalsCase)
        case energyAvailability(EnergyAvailabilityCase)
        case correctedTdee(EnergyCorrectedTdeeCase)
        case classifyDeficit(EnergyClassifyDeficitCase)
        case computeDailyBalance(EnergyDailyBalanceCase)
    }

    let payload: Payload

    init(from decoder: Decoder) throws {
        let root = try decoder.container(keyedBy: AnyKey.self)
        switch try root.decode(String.self, forKey: AnyKey("fn")) {
        case "trailingTdee": payload = .trailingTdee(try EnergyTrailingTdeeCase(from: decoder))
        case "deriveGoals": payload = .deriveGoals(try EnergyDeriveGoalsCase(from: decoder))
        case "energyAvailability": payload = .energyAvailability(try EnergyAvailabilityCase(from: decoder))
        case "correctedTdee": payload = .correctedTdee(try EnergyCorrectedTdeeCase(from: decoder))
        case "classifyDeficit": payload = .classifyDeficit(try EnergyClassifyDeficitCase(from: decoder))
        case "computeDailyBalance": payload = .computeDailyBalance(try EnergyDailyBalanceCase(from: decoder))
        case let other: throw EnergyFixture.Failure.unknownFunction(other)
        }
    }
}

enum EnergyGolden {
    /// Decoded once; the six `@Test(arguments:)` groups are views onto it.
    static let all = GoldenLoader.require(EnergyCase.self, file: EnergyFixture.file, group: "cases")

    static let trailingTdeeCases: [EnergyTrailingTdeeCase] = all.compactMap {
        if case .trailingTdee(let c) = $0.payload { return c } else { return nil }
    }
    static let deriveGoalsCases: [EnergyDeriveGoalsCase] = all.compactMap {
        if case .deriveGoals(let c) = $0.payload { return c } else { return nil }
    }
    static let energyAvailabilityCases: [EnergyAvailabilityCase] = all.compactMap {
        if case .energyAvailability(let c) = $0.payload { return c } else { return nil }
    }
    static let correctedTdeeCases: [EnergyCorrectedTdeeCase] = all.compactMap {
        if case .correctedTdee(let c) = $0.payload { return c } else { return nil }
    }
    static let classifyDeficitCases: [EnergyClassifyDeficitCase] = all.compactMap {
        if case .classifyDeficit(let c) = $0.payload { return c } else { return nil }
    }
    static let computeDailyBalanceCases: [EnergyDailyBalanceCase] = all.compactMap {
        if case .computeDailyBalance(let c) = $0.payload { return c } else { return nil }
    }
}

// MARK: - Tests

@Test(arguments: EnergyGolden.trailingTdeeCases)
func energyTrailingTdeeMatchesPython(_ c: EnergyTrailingTdeeCase) {
    let got = Energy.trailingTdee(c.trackedIntakes, wStart7d: c.wStart7d, wEnd7d: c.wEnd7d, spanDays: c.spanDays)
    #expect(energySame(got, c.expected), "trailingTdee: got \(got as Double?), want \(c.expected as Double?)")
}

@Test(arguments: EnergyGolden.deriveGoalsCases)
func energyDeriveGoalsMatchesPython(_ c: EnergyDeriveGoalsCase) {
    let got = Energy.deriveGoals(tdee: c.tdee, leanKg: c.leanKg, weightKg: c.weightKg)
    #expect(energySame(got.intakeKcal, c.intakeKcal), "intakeKcal: got \(got.intakeKcal), want \(c.intakeKcal)")
    #expect(energySame(got.proteinG, c.proteinG), "proteinG: got \(got.proteinG as Double?), want \(c.proteinG as Double?)")
    #expect(energySame(got.fatG, c.fatG), "fatG: got \(got.fatG as Double?), want \(c.fatG as Double?)")
    #expect(energySame(got.carbsG, c.carbsG), "carbsG: got \(got.carbsG as Double?), want \(c.carbsG as Double?)")
}

@Test(arguments: EnergyGolden.energyAvailabilityCases)
func energyAvailabilityMatchesPython(_ c: EnergyAvailabilityCase) {
    let got = Energy.energyAvailability(intakeKcal: c.intakeKcal, exerciseKcal: c.exerciseKcal, leanKg: c.leanKg)
    #expect(energySame(got, c.expected), "energyAvailability: got \(got as Double?), want \(c.expected as Double?)")
}

@Test(arguments: EnergyGolden.correctedTdeeCases)
func energyCorrectedTdeeMatchesPython(_ c: EnergyCorrectedTdeeCase) {
    let got = Energy.correctedTdee(totalKcal: c.totalKcal, kcalBurnedActive: c.kcalBurnedActive)
    #expect(energySame(got, c.expected), "correctedTdee: got \(got as Double?), want \(c.expected as Double?)")
}

@Test(arguments: EnergyGolden.classifyDeficitCases)
func energyClassifyDeficitMatchesPython(_ c: EnergyClassifyDeficitCase) {
    let got = Energy.classifyDeficit(c.deficitPct)
    #expect(got == c.expected, "classifyDeficit(\(c.deficitPct as Double?)): got \(got as DeficitClass?), want \(c.expected as DeficitClass?)")
}

@Test(arguments: EnergyGolden.computeDailyBalanceCases)
func energyComputeDailyBalanceMatchesPython(_ c: EnergyDailyBalanceCase) {
    let got = Energy.computeDailyBalance(
        date: c.date,
        kcalConsumed: c.kcalConsumed,
        totalKcal: c.totalKcal,
        mealsLogged: c.mealsLogged,
        kcalBurnedActive: c.kcalBurnedActive,
        tdeeEmpirical: c.tdeeEmpirical
    )
    let want = c.expected
    #expect(got.date == want.date)
    #expect(energySame(got.kcalConsumed, want.kcalConsumed), "kcalConsumed: got \(got.kcalConsumed as Double?), want \(want.kcalConsumed as Double?)")
    #expect(energySame(got.tdeeRaw, want.tdeeRaw), "tdeeRaw: got \(got.tdeeRaw as Double?), want \(want.tdeeRaw as Double?)")
    #expect(energySame(got.tdeeCorrected, want.tdeeCorrected), "tdeeCorrected: got \(got.tdeeCorrected as Double?), want \(want.tdeeCorrected as Double?)")
    #expect(energySame(got.deficitRaw, want.deficitRaw), "deficitRaw: got \(got.deficitRaw as Double?), want \(want.deficitRaw as Double?)")
    #expect(energySame(got.deficitCorrected, want.deficitCorrected), "deficitCorrected: got \(got.deficitCorrected as Double?), want \(want.deficitCorrected as Double?)")
    #expect(energySame(got.deficitPctRaw, want.deficitPctRaw), "deficitPctRaw: got \(got.deficitPctRaw as Double?), want \(want.deficitPctRaw as Double?)")
    #expect(energySame(got.deficitPctCorrected, want.deficitPctCorrected), "deficitPctCorrected: got \(got.deficitPctCorrected as Double?), want \(want.deficitPctCorrected as Double?)")
    #expect(got.deficitClass == want.deficitClass, "deficitClass: got \(got.deficitClass as DeficitClass?), want \(want.deficitClass as DeficitClass?)")
    #expect(got.mealsLogged == want.mealsLogged, "mealsLogged: got \(got.mealsLogged as Int?), want \(want.mealsLogged as Int?)")
}
