import Foundation
import Testing
@testable import JICompute

/// Parity tests for the KPI / decision gate.
///
/// Fixture is generated by `HealthTraining/scripts/parity/gen_golden_kpi.py`
/// from the live `app/planning/service.py` — ground truth is the Python code
/// itself. Never edit the fixture by hand; run
/// `HealthTraining/scripts/regen_goldens.py`.
///
/// 582 cases in one `cases` array, discriminated by `fn`:
/// safeFloat 77 · computeDerivedMetrics 62 · computeAverages 62 ·
/// isTrackedDay 41 · evalRule 133 · evaluateGate 107 · evaluateKpiGates 100.
/// Each golden case is one test case, so the count `swift test` prints IS the
/// golden count.
///
/// Every comparison goes through `KpiJSON`, which compares numbers on
/// `bitPattern` (so `-0.0` never passes as `0.0`) and dictionaries on their
/// full key set (so a missing or extra output key fails rather than being
/// ignored) — the structural equivalent of the TS oracle's `toEqual` plus
/// `Object.is`.

// MARK: - JSON model

/// A structural JSON value, used for both the golden inputs and the
/// expected/actual comparison. Prefixed `Kpi` because every lane's test file
/// shares one test module.
indirect enum KpiJSON: Decodable, Equatable, Sendable, CustomStringConvertible {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([KpiJSON])
    case object([String: KpiJSON])

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null; return }
        if let b = try? c.decode(Bool.self) { self = .bool(b); return }
        if let d = try? c.decode(Double.self) { self = .number(d); return }
        if let s = try? c.decode(String.self) { self = .string(s); return }
        if let a = try? c.decode([KpiJSON].self) { self = .array(a); return }
        if let o = try? c.decode([String: KpiJSON].self) { self = .object(o); return }
        throw DecodingError.dataCorruptedError(in: c, debugDescription: "unsupported JSON value")
    }

    /// Numbers compare on `bitPattern`: `0.0 == -0.0` in IEEE-754, and
    /// preserving `-0.0` through `round()` is a stated parity requirement.
    static func == (lhs: KpiJSON, rhs: KpiJSON) -> Bool {
        switch (lhs, rhs) {
        case (.null, .null): return true
        case let (.bool(a), .bool(b)): return a == b
        case let (.number(a), .number(b)): return a.bitPattern == b.bitPattern
        case let (.string(a), .string(b)): return a == b
        case let (.array(a), .array(b)): return a == b
        case let (.object(a), .object(b)): return a == b
        default: return false
        }
    }

    var description: String {
        switch self {
        case .null: return "null"
        case .bool(let b): return "\(b)"
        case .number(let d): return pythonFloatString(d)
        case .string(let s): return "\"\(s)\""
        case .array(let a): return "[" + a.map(\.description).joined(separator: ", ") + "]"
        case .object(let o):
            return "{" + o.keys.sorted().map { "\($0): \(o[$0]!.description)" }.joined(separator: ", ") + "}"
        }
    }

    // Accessors — a golden fixture that does not match the shape is a defect,
    // so these trap with a diagnostic rather than returning a silent default.
    var asObject: [String: KpiJSON] {
        guard case .object(let o) = self else { fatalError("expected a JSON object, got \(self)") }
        return o
    }

    var asArray: [KpiJSON] {
        guard case .array(let a) = self else { fatalError("expected a JSON array, got \(self)") }
        return a
    }

    var asString: String {
        guard case .string(let s) = self else { fatalError("expected a JSON string, got \(self)") }
        return s
    }

    /// `null` -> nil, number -> value. Anything else is a fixture defect.
    var asOptionalDouble: Double? {
        switch self {
        case .null: return nil
        case .number(let d): return d
        default: fatalError("expected a JSON number or null, got \(self)")
        }
    }

    static func number(_ value: Double?) -> KpiJSON { value.map { .number($0) } ?? .null }
}

// MARK: - Fixture

struct KpiCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["fn", "input", "output"]

    let fn: String
    let input: KpiJSON
    let output: KpiJSON

    var testDescription: String { "\(fn)(\(input))" }
}

enum KpiGolden {
    static let all = GoldenLoader.require(KpiCase.self, file: "kpi.golden", group: "cases")

    static func cases(_ fn: String) -> [KpiCase] { all.filter { $0.fn == fn } }

    static let safeFloat = cases("safeFloat")
    static let computeDerivedMetrics = cases("computeDerivedMetrics")
    static let computeAverages = cases("computeAverages")
    static let isTrackedDay = cases("isTrackedDay")
    static let evalRule = cases("evalRule")
    static let evaluateKpiGates = cases("evaluateKpiGates")
    static let evaluateGate = cases("evaluateGate")
}

// MARK: - Decoding golden inputs

/// The golden `input` object must carry exactly the keys the port reads — an
/// added generator argument has to fail loudly, the same contract
/// `GoldenLoader`'s `allowedKeys` enforces one level up.
private func kpiInput(_ c: KpiCase, _ keys: Set<String>) -> [String: KpiJSON] {
    let obj = c.input.asObject
    #expect(Set(obj.keys) == keys, "\(c.fn) input keys \(Set(obj.keys).sorted()) != \(keys.sorted())")
    return obj
}

private func kpiRow(_ json: KpiJSON) -> KpiMetricRow {
    var values: [String: Double?] = [:]
    for (k, v) in json.asObject { values.updateValue(v.asOptionalDouble, forKey: k) }
    return KpiMetricRow(values)
}

private func kpiRows(_ json: KpiJSON) -> [KpiMetricRow] { json.asArray.map(kpiRow) }

private func kpiRule(_ json: KpiJSON) -> KpiRule {
    let o = json.asObject
    // `target_id` is a DB column the compute surface deliberately ignores; any
    // other unexpected key is a fixture the port has not caught up with.
    let known: Set<String> = ["metric", "operator", "threshold", "threshold_hi", "description", "target_id"]
    #expect(Set(o.keys).isSubset(of: known), "unknown kpiTarget key(s) \(Set(o.keys).subtracting(known).sorted())")
    return KpiRule(
        metric: o["metric"]!.asString,
        operator: o["operator"]!.asString,
        threshold: o["threshold"].flatMap(\.asOptionalDouble),
        thresholdHi: o["threshold_hi"].flatMap(\.asOptionalDouble),
        description: o["description"].map(\.asString) ?? ""
    )
}

/// Rebuild a `DerivedMetrics` from the fixture's `derived` dict (evalRule's
/// input). An empty object is Python's bare `{}`.
private func kpiDerived(_ json: KpiJSON) -> DerivedMetrics {
    let o = json.asObject
    if o.isEmpty { return .empty }
    func num(_ key: String) -> Double? { o[key].flatMap(\.asOptionalDouble) }
    var trends: TrendMap?
    if let t = o["trends"] {
        let d = t.asObject
        func dir(_ key: String) -> TrendDirection { TrendDirection(rawValue: d[key]!.asString)! }
        trends = TrendMap(kcal: dir("kcal"), protein: dir("protein"), rhr: dir("rhr"),
                          sleep: dir("sleep"), acwr: dir("acwr"), bodyBattery: dir("body_battery"),
                          kcalBurned: dir("kcal_burned"))
    }
    return DerivedMetrics(
        isEmpty: false,
        acwr: num("acwr"), avgKcal7d: num("avg_kcal_7d"), avgProtein7d: num("avg_protein_7d"),
        sleepScore7d: num("sleep_score_7d"), avgWeightKg: num("avg_weight_kg"),
        avgRhrBpm: num("avg_rhr_bpm"), avgSteps: num("avg_steps"),
        avgBodyBattery: num("avg_body_battery"), avgKcalBurned7d: num("avg_kcal_burned_7d"),
        avgKcalGoalRatio: num("avg_kcal_goal_ratio"), proteinPerKg: num("protein_per_kg"),
        avgKcalDeficit7d: num("avg_kcal_deficit_7d"),
        estWeeklyWeightChangeKg: num("est_weekly_weight_change_kg"),
        trends: trends
    )
}

// MARK: - Encoding results back to JSON

private func kpiJSON(_ trends: TrendMap) -> KpiJSON {
    .object([
        "kcal": .string(trends.kcal.rawValue),
        "protein": .string(trends.protein.rawValue),
        "rhr": .string(trends.rhr.rawValue),
        "sleep": .string(trends.sleep.rawValue),
        "acwr": .string(trends.acwr.rawValue),
        "body_battery": .string(trends.bodyBattery.rawValue),
        "kcal_burned": .string(trends.kcalBurned.rawValue),
    ])
}

private func kpiJSON(_ d: DerivedMetrics) -> KpiJSON {
    guard !d.isEmpty else { return .object([:]) }
    var o: [String: KpiJSON] = [
        "acwr": .number(d.acwr),
        "avg_kcal_7d": .number(d.avgKcal7d),
        "avg_protein_7d": .number(d.avgProtein7d),
        "sleep_score_7d": .number(d.sleepScore7d),
        "avg_weight_kg": .number(d.avgWeightKg),
        "avg_rhr_bpm": .number(d.avgRhrBpm),
        "avg_steps": .number(d.avgSteps),
        "avg_body_battery": .number(d.avgBodyBattery),
        "avg_kcal_burned_7d": .number(d.avgKcalBurned7d),
        "avg_kcal_goal_ratio": .number(d.avgKcalGoalRatio),
        "protein_per_kg": .number(d.proteinPerKg),
        "avg_kcal_deficit_7d": .number(d.avgKcalDeficit7d),
        "est_weekly_weight_change_kg": .number(d.estWeeklyWeightChangeKg),
    ]
    if let trends = d.trends { o["trends"] = kpiJSON(trends) }
    return .object(o)
}

private func kpiJSON(_ a: AveragesResult) -> KpiJSON {
    .object([
        "avg_kcal": .number(a.avgKcal),
        "avg_protein_g": .number(a.avgProteinG),
        "avg_rhr": .number(a.avgRhr),
        "avg_sleep_score": .number(a.avgSleepScore),
        "acwr": .number(a.acwr),
        "avg_kcal_7d": .number(a.avgKcal7d),
        "avg_protein_7d": .number(a.avgProtein7d),
        "sleep_score_7d": .number(a.sleepScore7d),
        "avg_weight_kg": .number(a.avgWeightKg),
        "avg_rhr_bpm": .number(a.avgRhrBpm),
        "avg_steps": .number(a.avgSteps),
        "avg_body_battery": .number(a.avgBodyBattery),
        "avg_kcal_burned_7d": .number(a.avgKcalBurned7d),
        "avg_kcal_goal_ratio": .number(a.avgKcalGoalRatio),
        "protein_per_kg": .number(a.proteinPerKg),
        "avg_kcal_deficit_7d": .number(a.avgKcalDeficit7d),
        "est_weekly_weight_change_kg": .number(a.estWeeklyWeightChangeKg),
        "trends": kpiJSON(a.trends),
    ])
}

private func kpiJSON(_ r: GateResult) -> KpiJSON {
    .object([
        "recommendation": .string(r.recommendation.rawValue),
        "triggered_rules": .array(r.triggeredRules.map(KpiJSON.string)),
        "suggestions": .array(r.suggestions.map(KpiJSON.string)),
    ])
}

private func kpiJSON(_ d: GateDecision) -> KpiJSON {
    .object([
        "recommendation": .string(d.recommendation.rawValue),
        "triggered_rules": .array(d.triggeredRules.map(KpiJSON.string)),
        "suggestions": .array(d.suggestions.map(KpiJSON.string)),
        "tracked_days": .number(Double(d.trackedDays)),
        "total_days": .number(Double(d.totalDays)),
    ])
}

// MARK: - Tests

/// `_safe_float` — the nil short-circuit, and `-0.0` surviving unchanged.
@Test(arguments: KpiGolden.safeFloat)
func safeFloatMatchesPython(_ c: KpiCase) {
    let input = kpiInput(c, ["v"])
    let got = safeFloat(input["v"]!.asOptionalDouble)
    #expect(KpiJSON.number(got) == c.output, "safeFloat(\(input["v"]!)): got \(KpiJSON.number(got)), want \(c.output)")
}

/// `_compute_derived_metrics` — including the bare `{}` for an empty window.
@Test(arguments: KpiGolden.computeDerivedMetrics)
func computeDerivedMetricsMatchesPython(_ c: KpiCase) {
    let rows = kpiRows(kpiInput(c, ["rows"])["rows"]!)
    let got = kpiJSON(computeDerivedMetrics(rows))
    #expect(got == c.output, "computeDerivedMetrics: got \(got), want \(c.output)")
}

/// `compute_averages` — the `{**_empty, **derived}` merge plus the 4 aliases.
@Test(arguments: KpiGolden.computeAverages)
func computeAveragesMatchesPython(_ c: KpiCase) {
    let rows = kpiRows(kpiInput(c, ["rows"])["rows"]!)
    let got = kpiJSON(computeAverages(rows))
    #expect(got == c.output, "computeAverages: got \(got), want \(c.output)")
}

/// `is_tracked_day` — the strict-day boundaries and the `or 0` falsiness.
@Test(arguments: KpiGolden.isTrackedDay)
func isTrackedDayMatchesPython(_ c: KpiCase) {
    let row = kpiRow(kpiInput(c, ["row"])["row"]!)
    let got = isTrackedDay(row)
    #expect(KpiJSON.bool(got) == c.output, "isTrackedDay(\(c.input)): got \(got), want \(c.output)")
}

/// `_eval_rule` — every operator, the count-rule day-count boundaries, and the
/// three-valued result (`true` / `false` / not-applicable).
@Test(arguments: KpiGolden.evalRule)
func evalRuleMatchesPython(_ c: KpiCase) {
    let input = kpiInput(c, ["metricName", "operator", "threshold", "thresholdHi", "derived", "metrics"])
    let metrics: [KpiMetricRow]? = input["metrics"]! == .null ? nil : kpiRows(input["metrics"]!)
    let got = evalRule(
        metricName: input["metricName"]!.asString,
        operator: input["operator"]!.asString,
        threshold: input["threshold"]!.asOptionalDouble,
        thresholdHi: input["thresholdHi"]!.asOptionalDouble,
        derived: kpiDerived(input["derived"]!),
        metrics: metrics
    )
    let asJSON = got.map(KpiJSON.bool) ?? .null
    #expect(asJSON == c.output, "evalRule: got \(asJSON), want \(c.output)")
}

/// `evaluate_kpi_gates` — recommendation, the first-rule-wins ordering, and the
/// triggered-rule strings byte-exact (`==` on `String`, no normalisation).
@Test(arguments: KpiGolden.evaluateKpiGates)
func evaluateKpiGatesMatchesPython(_ c: KpiCase) {
    let input = kpiInput(c, ["metrics", "kpiTargets"])
    let got = kpiJSON(evaluateKpiGates(kpiRows(input["metrics"]!), input["kpiTargets"]!.asArray.map(kpiRule)))
    #expect(got == c.output, "evaluateKpiGates: got \(got), want \(c.output)")
}

/// `evaluate_gate` — the tracking-quality suppression on top of the KPI gate.
@Test(arguments: KpiGolden.evaluateGate)
func evaluateGateMatchesPython(_ c: KpiCase) {
    let input = kpiInput(c, ["metrics", "kpiTargets"])
    let got = kpiJSON(evaluateGate(kpiRows(input["metrics"]!), input["kpiTargets"]!.asArray.map(kpiRule)))
    #expect(got == c.output, "evaluateGate: got \(got), want \(c.output)")
}

/// The fixture must contain exactly the case counts the wave card fixes, so a
/// regenerated golden that silently drops a group fails here rather than
/// passing with fewer tests.
@Test func kpiGoldenCaseCounts() {
    #expect(KpiGolden.all.count == 582)
    #expect(KpiGolden.safeFloat.count == 77)
    #expect(KpiGolden.computeDerivedMetrics.count == 62)
    #expect(KpiGolden.computeAverages.count == 62)
    #expect(KpiGolden.isTrackedDay.count == 41)
    #expect(KpiGolden.evalRule.count == 133)
    #expect(KpiGolden.evaluateKpiGates.count == 100)
    #expect(KpiGolden.evaluateGate.count == 107)
}

/// The three defaults that ship with the package are literal DB data — a typo
/// here silently changes every offline verdict.
@Test func kpiDefaultsMatchThePythonModuleConstants() {
    #expect(defaultKpiConfig.progressKcalRatioMin == 0.80)
    #expect(defaultKpiConfig.progressKcalRatioMax == 1.10)
    #expect(defaultKpiConfig.progressProteinPerKg == 2.0)
    #expect(defaultKpiConfig.trackingKcalMin == 1200)
    #expect(defaultKpiConfig.trackingMealsMin == 3)
    #expect(defaultKpiConfig.minTrackedDays == 4)
    #expect(defaultKpiConfig.countRuleFields["avg_kcal_7d"]! == (field: "kcal_consumed", minDays: 5))
    #expect(defaultKpiConfig.countRuleFields["avg_protein_7d"]! == (field: "protein_g", minDays: 5))
    #expect(defaultKpiConfig.countRuleFields["sleep_score_7d"]! == (field: "sleep_score", minDays: 4))
    #expect(defaultKpiRules.count == 6)
    #expect(defaultKpiRules.map(\.metric) == ["acwr", "avg_kcal_7d", "avg_protein_7d", "sleep_score_7d", "acwr", "acwr"])
    #expect(defaultKpiRules.map(\.operator) == [">", "<", "<", "<", "<", "between"])
    #expect(defaultKpiRules.map(\.threshold) == [1.30, 1600.0, 130.0, 55.0, 0.80, 0.80])
    #expect(defaultKpiRules.last!.thresholdHi == 1.30)
}
