import Foundation
import Testing
@testable import JICompute

/// Parity tests for the morning readiness gate.
///
/// Fixture is generated by `HealthTraining/scripts/parity/gen_golden_morning.py`
/// — ground truth is `scripts/morning_go.py` executed by the Python interpreter.
/// Never edit the fixture by hand; run `HealthTraining/scripts/regen_goldens.py`.
///
/// 988 golden cases across 13 case groups: `sessionDoneCases` 216 ·
/// `reducedCompliantCases` 12 · `liftFlagsCases` 51 · `trendKgWkCases` 70 ·
/// `consecutiveDoseIndexCases` 36 · `rhrCarriedOverCases` 6 ·
/// `vitalsPresentCases` 7 · `vitalsLineCases` 26 · `fmtVsCases` 47 ·
/// `prevFromStateCases` 5 · `streakCases` 29 · `bestStreakCases` 29 ·
/// `evaluateCases` 454. Each golden case is one test case, so the count
/// `swift test --filter MorningGate` prints is the golden count PLUS ONE:
/// `morningGateSourcesAvoidAmbientClockAPIs` is a non-golden source-hygiene
/// guard required by the W6 card's L1 exit criteria ("no `Date()`/
/// `TimeZone.current` in Sources (grep test)").
///
/// Verdict and condition strings are compared with plain `==` on `String` — no
/// normalisation, no trimming, no Unicode folding.

// MARK: - Ordered-object reading
//
// `liftFlags` walks the lift map in insertion order and that order decides the
// order of the flag strings it returns (six golden cases have two lifts that
// both contribute). `JSONDecoder`'s `allKeys` does NOT preserve document order
// — it reports the hash order of the parsed object — so the ordered key list is
// read from the fixture bytes with the minimal scanner below and used to
// linearise the decoded map.

private enum OrderedJSON {
    case object([(key: String, value: OrderedJSON)])
    case array([OrderedJSON])
    case scalar

    func child(_ key: String) -> OrderedJSON? {
        guard case .object(let members) = self else { return nil }
        return members.first { $0.key == key }?.value
    }

    var elements: [OrderedJSON] {
        guard case .array(let elements) = self else { return [] }
        return elements
    }

    var keyOrder: [String] {
        guard case .object(let members) = self else { return [] }
        return members.map(\.key)
    }
}

/// Structure-only JSON reader: it records object key order and array shape and
/// discards every scalar value (those come from `JSONDecoder`).
private struct OrderedJSONReader {
    private let bytes: [UInt8]
    private var index = 0

    private init(_ data: Data) { bytes = Array(data) }

    static func parse(_ data: Data) -> OrderedJSON {
        var reader = OrderedJSONReader(data)
        return reader.parseValue()
    }

    private mutating func skipWhitespace() {
        while index < bytes.count, bytes[index] == 0x20 || bytes[index] == 0x09 || bytes[index] == 0x0A || bytes[index] == 0x0D {
            index += 1
        }
    }

    private mutating func parseValue() -> OrderedJSON {
        skipWhitespace()
        guard index < bytes.count else { return .scalar }
        switch bytes[index] {
        case UInt8(ascii: "{"):
            index += 1
            var members: [(key: String, value: OrderedJSON)] = []
            skipWhitespace()
            if index < bytes.count, bytes[index] == UInt8(ascii: "}") {
                index += 1
                return .object(members)
            }
            while index < bytes.count {
                skipWhitespace()
                let key = parseString()
                skipWhitespace()
                if index < bytes.count, bytes[index] == UInt8(ascii: ":") { index += 1 }
                members.append((key, parseValue()))
                skipWhitespace()
                if index < bytes.count, bytes[index] == UInt8(ascii: ",") {
                    index += 1
                    continue
                }
                if index < bytes.count, bytes[index] == UInt8(ascii: "}") { index += 1 }
                break
            }
            return .object(members)
        case UInt8(ascii: "["):
            index += 1
            var elements: [OrderedJSON] = []
            skipWhitespace()
            if index < bytes.count, bytes[index] == UInt8(ascii: "]") {
                index += 1
                return .array(elements)
            }
            while index < bytes.count {
                elements.append(parseValue())
                skipWhitespace()
                if index < bytes.count, bytes[index] == UInt8(ascii: ",") {
                    index += 1
                    continue
                }
                if index < bytes.count, bytes[index] == UInt8(ascii: "]") { index += 1 }
                break
            }
            return .array(elements)
        case UInt8(ascii: "\""):
            _ = parseString()
            return .scalar
        default:
            while index < bytes.count, !isDelimiter(bytes[index]) { index += 1 }
            return .scalar
        }
    }

    private func isDelimiter(_ byte: UInt8) -> Bool {
        byte == UInt8(ascii: ",") || byte == UInt8(ascii: "}") || byte == UInt8(ascii: "]")
            || byte == 0x20 || byte == 0x09 || byte == 0x0A || byte == 0x0D
    }

    private mutating func parseString() -> String {
        guard index < bytes.count, bytes[index] == UInt8(ascii: "\"") else { return "" }
        index += 1
        var utf8: [UInt8] = []
        while index < bytes.count {
            let byte = bytes[index]
            if byte == UInt8(ascii: "\"") {
                index += 1
                break
            }
            if byte == UInt8(ascii: "\\") {
                index += 1
                guard index < bytes.count else { break }
                let escape = bytes[index]
                index += 1
                switch escape {
                case UInt8(ascii: "n"): utf8.append(0x0A)
                case UInt8(ascii: "t"): utf8.append(0x09)
                case UInt8(ascii: "r"): utf8.append(0x0D)
                case UInt8(ascii: "b"): utf8.append(0x08)
                case UInt8(ascii: "f"): utf8.append(0x0C)
                case UInt8(ascii: "u"):
                    var code = 0
                    for _ in 0..<4 where index < bytes.count {
                        code = code * 16 + hexValue(bytes[index])
                        index += 1
                    }
                    if let scalar = Unicode.Scalar(code) { utf8.append(contentsOf: Array(String(scalar).utf8)) }
                default: utf8.append(escape)
                }
                continue
            }
            utf8.append(byte)
            index += 1
        }
        return String(decoding: utf8, as: UTF8.self)
    }

    private func hexValue(_ byte: UInt8) -> Int {
        switch byte {
        case UInt8(ascii: "0")...UInt8(ascii: "9"): return Int(byte - UInt8(ascii: "0"))
        case UInt8(ascii: "a")...UInt8(ascii: "f"): return Int(byte - UInt8(ascii: "a")) + 10
        case UInt8(ascii: "A")...UInt8(ascii: "F"): return Int(byte - UInt8(ascii: "A")) + 10
        default: return 0
        }
    }
}

private enum MorningFixtureOrder {
    static let root: OrderedJSON = {
        guard let url = Bundle.module.url(
            forResource: "morning.golden",
            withExtension: "json",
            subdirectory: "Resources/golden"
        ), let data = try? Data(contentsOf: url) else {
            fatalError("golden fixture morning.golden.json is not in the test bundle")
        }
        return OrderedJSONReader.parse(data)
    }()

    /// Document order of the keys of the object at `path` inside each case of
    /// `group`, one entry per case, `[]` where the object is absent.
    static func keyOrders(group: String, path: [String]) -> [[String]] {
        (root.child(group)?.elements ?? []).map { element in
            var node: OrderedJSON? = element
            for step in path { node = node?.child(step) }
            return node?.keyOrder ?? []
        }
    }

    /// Linearise a decoded lift map with the fixture's own key order.
    static func lifts(_ map: [String: [LiftSessionFixture]], order: [String]) -> [LiftHistory] {
        precondition(
            Set(order) == Set(map.keys),
            "lift key order \(order) does not match the decoded lift map \(map.keys.sorted()) — fixture misalignment"
        )
        return order.map { LiftHistory(name: $0, sessions: (map[$0] ?? []).map(\.session)) }
    }
}

// MARK: - Shared fixture pieces

struct LiftSessionFixture: Decodable, Sendable {
    let date: String
    let volume: Double
    let minReps: Int?
    let topKg: Double

    enum CodingKeys: String, CodingKey {
        case date
        case volume
        case minReps = "min_reps"
        case topKg = "top_kg"
    }

    var session: BenchmarkLiftSession {
        BenchmarkLiftSession(date: date, volume: volume, minReps: minReps, topKg: topKg)
    }
}

struct VitalsFixture: Decodable, Sendable {
    let sleep: Int?
    let sleepDurationH: Double?
    let hrv: Int?
    let hrvStatus: String?
    let rhr: Int?
    let rhrDate: String?
    let stepsYesterday: Int?

    enum CodingKeys: String, CodingKey {
        case sleep
        case sleepDurationH = "sleep_duration_h"
        case hrv
        case hrvStatus = "hrv_status"
        case rhr
        case rhrDate = "rhr_date"
        case stepsYesterday = "steps_yesterday"
    }

    var vitals: MorningVitals {
        MorningVitals(
            sleep: sleep,
            sleepDurationH: sleepDurationH,
            hrv: hrv,
            hrvStatus: hrvStatus,
            rhr: rhr,
            rhrDate: rhrDate,
            stepsYesterday: stepsYesterday
        )
    }
}

struct PrevStateFixture: Decodable, Sendable {
    let hrvLow: Bool?
    let rhrHigh: Bool?
    let rhrDate: String?
    let sleepLow: Bool?

    enum CodingKeys: String, CodingKey {
        case hrvLow = "hrv_low"
        case rhrHigh = "rhr_high"
        case rhrDate = "rhr_date"
        case sleepLow = "sleep_low"
    }

    var prevState: MorningGatePrevState {
        MorningGatePrevState(hrvLow: hrvLow, rhrHigh: rhrHigh, rhrDate: rhrDate, sleepLow: sleepLow)
    }
}

struct StateFixture: Decodable, Sendable {
    let date: String?
    let hrvLow: Bool?
    let rhrHigh: Bool?
    let rhrDate: String?
    let sleepLow: Bool?
    let prev: PrevStateFixture?

    enum CodingKeys: String, CodingKey {
        case date
        case hrvLow = "hrv_low"
        case rhrHigh = "rhr_high"
        case rhrDate = "rhr_date"
        case sleepLow = "sleep_low"
        case prev
    }

    var state: MorningGateState {
        MorningGateState(
            date: date,
            hrvLow: hrvLow,
            rhrHigh: rhrHigh,
            rhrDate: rhrDate,
            sleepLow: sleepLow,
            prev: prev?.prevState
        )
    }
}

struct NewStateFixture: Decodable, Sendable {
    let date: String
    let hrvLow: Bool
    let rhrHigh: Bool
    let rhrDate: String?
    let sleepLow: Bool

    enum CodingKeys: String, CodingKey {
        case date
        case hrvLow = "hrv_low"
        case rhrHigh = "rhr_high"
        case rhrDate = "rhr_date"
        case sleepLow = "sleep_low"
    }

    var newState: MorningGateNewState {
        MorningGateNewState(date: date, hrvLow: hrvLow, rhrHigh: rhrHigh, rhrDate: rhrDate, sleepLow: sleepLow)
    }
}

struct DbFixture: Decodable, Sendable {
    let yKcal: Double?
    let yProtein: Double?
    let yCarbs: Double?
    let yFat: Double?
    let yKcalGoal: Double?
    let yProteinGoal: Double?
    let yCarbsGoal: Double?
    let yFatGoal: Double?
    let latestWeight: Double?
    let latestBf: Double?
    let weightTrendWk: Double?
    let lifts: [String: [LiftSessionFixture]]?
    let yResp: Double?
    let respBaseline: Double?
    let effRecent: Double?
    let effPrior: Double?
    let kpiDays: Int?
    let trackRate: Int?
    let trackStreak: Int?
    let trackBest: Int?
    let stepRate: Int?
    let stepStreak: Int?
    let stepBest: Int?
    let exRate: Int?
    let exStreak: Int?
    let exBest: Int?
    let experimentIntervals: Int?
    let experimentTarget: Int?
    let carbs3dAvg: Double?
    let dbOk: Bool?
    let stale: Bool?

    enum CodingKeys: String, CodingKey {
        case yKcal = "y_kcal"
        case yProtein = "y_protein"
        case yCarbs = "y_carbs"
        case yFat = "y_fat"
        case yKcalGoal = "y_kcal_goal"
        case yProteinGoal = "y_protein_goal"
        case yCarbsGoal = "y_carbs_goal"
        case yFatGoal = "y_fat_goal"
        case latestWeight = "latest_weight"
        case latestBf = "latest_bf"
        case weightTrendWk = "weight_trend_wk"
        case lifts
        case yResp = "y_resp"
        case respBaseline = "resp_baseline"
        case effRecent = "eff_recent"
        case effPrior = "eff_prior"
        case kpiDays = "kpi_days"
        case trackRate = "track_rate"
        case trackStreak = "track_streak"
        case trackBest = "track_best"
        case stepRate = "step_rate"
        case stepStreak = "step_streak"
        case stepBest = "step_best"
        case exRate = "ex_rate"
        case exStreak = "ex_streak"
        case exBest = "ex_best"
        case experimentIntervals = "experiment_intervals"
        case experimentTarget = "experiment_target"
        case carbs3dAvg = "carbs_3d_avg"
        case dbOk = "_db_ok"
        case stale = "_stale"
    }

    func db(lifts orderedLifts: [LiftHistory]) -> MorningGateDb {
        MorningGateDb(
            yKcal: yKcal,
            yProtein: yProtein,
            yCarbs: yCarbs,
            yFat: yFat,
            yKcalGoal: yKcalGoal,
            yProteinGoal: yProteinGoal,
            yCarbsGoal: yCarbsGoal,
            yFatGoal: yFatGoal,
            latestWeight: latestWeight,
            latestBf: latestBf,
            weightTrendWk: weightTrendWk,
            lifts: orderedLifts,
            yResp: yResp,
            respBaseline: respBaseline,
            effRecent: effRecent,
            effPrior: effPrior,
            kpiDays: kpiDays,
            trackRate: trackRate,
            trackStreak: trackStreak,
            trackBest: trackBest,
            stepRate: stepRate,
            stepStreak: stepStreak,
            stepBest: stepBest,
            exRate: exRate,
            exStreak: exStreak,
            exBest: exBest,
            experimentIntervals: experimentIntervals,
            experimentTarget: experimentTarget,
            carbs3dAvg: carbs3dAvg,
            dbOk: dbOk,
            stale: stale
        )
    }
}

/// A `(date, weight)` cell: the weight column is `numeric`, so some rows carry
/// a decimal string and some a JSON number.
enum TrendCellFixture: Decodable, Sendable {
    case text(String)
    case number(Double)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let text = try? container.decode(String.self) {
            self = .text(text)
        } else {
            self = .number(try container.decode(Double.self))
        }
    }

    var text: String {
        switch self {
        case .text(let value): return value
        case .number(let value): return "\(value)"
        }
    }
}

// MARK: - Case groups

struct SessionDoneCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["stype", "doneTypes", "stepOk", "longWalk", "expected"]

    let stype: String
    let doneTypes: [String]
    let stepOk: Bool
    let longWalk: Bool
    let expected: Bool

    var testDescription: String { "\(stype) done=\(doneTypes) step=\(stepOk) walk=\(longWalk)" }
}

struct ReducedCompliantCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["dayTypes", "longWalk", "expected"]

    let dayTypes: [String]
    let longWalk: Bool
    let expected: Bool

    var testDescription: String { "\(dayTypes) walk=\(longWalk)" }
}

struct LiftFlagsCase: GoldenCase {
    static let allowedKeys: Set<String> = ["lifts", "reds", "notes"]

    let lifts: [String: [LiftSessionFixture]]
    let reds: [String]
    let notes: [String]
}

/// `LiftFlagsCase` with the lift map linearised into the fixture's key order.
struct LiftFlagsFixture: Sendable, CustomTestStringConvertible {
    let lifts: [LiftHistory]
    let reds: [String]
    let notes: [String]

    var testDescription: String { lifts.map { "\($0.name)×\($0.sessions.count)" }.joined(separator: "+") }
}

struct TrendKgWkCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["rows", "expected"]

    let rows: [[TrendCellFixture]]
    let expected: Double?

    var trendRows: [TrendRow] {
        rows.map { cells in
            let date = cells[0].text
            switch cells[1] {
            case .number(let value): return TrendRow(date: date, weight: value)
            case .text(let value): return TrendRow(date: date, weightText: value)
            }
        }
    }

    var testDescription: String { "\(rows.count) rows -> \(expected.map { "\($0)" } ?? "nil")" }
}

struct ConsecutiveDoseIndexCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["day", "dosed", "expected"]

    let day: String
    let dosed: [String]
    let expected: Int

    var testDescription: String { "\(day) in \(dosed.count) dosed" }
}

struct RhrCarriedOverCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["m", "today", "expected"]

    let m: VitalsFixture
    let today: String
    let expected: Bool

    var testDescription: String { "\(today) rhr_date=\(m.rhrDate ?? "nil")" }
}

struct VitalsPresentCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["m", "expected"]

    let m: VitalsFixture
    let expected: Bool

    var testDescription: String { "sleep=\(m.sleep.map(String.init) ?? "nil") hrv=\(m.hrv.map(String.init) ?? "nil")" }
}

struct VitalsLineCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["m", "today", "expected"]

    let m: VitalsFixture
    let today: String
    let expected: String

    var testDescription: String { "\(today): \(expected)" }
}

struct FmtVsCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["v", "goal", "suffix", "expected"]

    let v: Double?
    let goal: Double?
    let suffix: String
    let expected: String

    var testDescription: String { expected }
}

struct PrevFromStateCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["state", "today", "expected"]

    let state: StateFixture
    let today: String
    let expected: PrevStateFixture

    var testDescription: String { "state.date=\(state.date ?? "nil") today=\(today)" }
}

struct StreakCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["okDays", "end", "expected"]

    let okDays: [String]
    let end: String
    let expected: Int

    var testDescription: String { "\(okDays.count) days ending \(end)" }
}

struct BestStreakCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["okDays", "expected"]

    let okDays: [String]
    let expected: Int

    var testDescription: String { "\(okDays.count) days -> \(expected)" }
}

struct EvaluateCase: GoldenCase {
    static let allowedKeys: Set<String> = [
        "today", "m", "db", "state", "dosedDates", "verdict", "conditions", "newState",
    ]

    let today: String
    let m: VitalsFixture
    let db: DbFixture
    let state: PrevStateFixture
    let dosedDates: [String]
    let verdict: String
    let conditions: [String]
    let newState: NewStateFixture
}

/// `EvaluateCase` with `db.lifts` linearised into the fixture's key order.
struct EvaluateFixture: Sendable, CustomTestStringConvertible {
    let today: String
    let vitals: MorningVitals
    let db: MorningGateDb
    let state: MorningGatePrevState
    let dosedDates: [String]
    let verdict: String
    let conditions: [String]
    let newState: MorningGateNewState

    var testDescription: String { "\(today) -> \(verdict)" }
}

enum MorningGolden {
    private static let file = "morning.golden"

    static let sessionDoneCases = GoldenLoader.require(SessionDoneCase.self, file: file, group: "sessionDoneCases")
    static let reducedCompliantCases = GoldenLoader.require(ReducedCompliantCase.self, file: file, group: "reducedCompliantCases")
    static let trendKgWkCases = GoldenLoader.require(TrendKgWkCase.self, file: file, group: "trendKgWkCases")
    static let consecutiveDoseIndexCases = GoldenLoader.require(ConsecutiveDoseIndexCase.self, file: file, group: "consecutiveDoseIndexCases")
    static let rhrCarriedOverCases = GoldenLoader.require(RhrCarriedOverCase.self, file: file, group: "rhrCarriedOverCases")
    static let vitalsPresentCases = GoldenLoader.require(VitalsPresentCase.self, file: file, group: "vitalsPresentCases")
    static let vitalsLineCases = GoldenLoader.require(VitalsLineCase.self, file: file, group: "vitalsLineCases")
    static let fmtVsCases = GoldenLoader.require(FmtVsCase.self, file: file, group: "fmtVsCases")
    static let prevFromStateCases = GoldenLoader.require(PrevFromStateCase.self, file: file, group: "prevFromStateCases")
    static let streakCases = GoldenLoader.require(StreakCase.self, file: file, group: "streakCases")
    static let bestStreakCases = GoldenLoader.require(BestStreakCase.self, file: file, group: "bestStreakCases")

    static let liftFlagsCases: [LiftFlagsFixture] = {
        let cases = GoldenLoader.require(LiftFlagsCase.self, file: file, group: "liftFlagsCases")
        let orders = MorningFixtureOrder.keyOrders(group: "liftFlagsCases", path: ["lifts"])
        precondition(cases.count == orders.count, "liftFlagsCases/key-order count mismatch")
        return zip(cases, orders).map { golden, order in
            LiftFlagsFixture(
                lifts: MorningFixtureOrder.lifts(golden.lifts, order: order),
                reds: golden.reds,
                notes: golden.notes
            )
        }
    }()

    static let evaluateCases: [EvaluateFixture] = {
        let cases = GoldenLoader.require(EvaluateCase.self, file: file, group: "evaluateCases")
        let orders = MorningFixtureOrder.keyOrders(group: "evaluateCases", path: ["db", "lifts"])
        precondition(cases.count == orders.count, "evaluateCases/key-order count mismatch")
        return zip(cases, orders).map { golden, order in
            EvaluateFixture(
                today: golden.today,
                vitals: golden.m.vitals,
                db: golden.db.db(lifts: MorningFixtureOrder.lifts(golden.db.lifts ?? [:], order: order)),
                state: golden.state.prevState,
                dosedDates: golden.dosedDates,
                verdict: golden.verdict,
                conditions: golden.conditions,
                newState: golden.newState.newState
            )
        }
    }()
}

// MARK: - Tests

@Test(arguments: MorningGolden.sessionDoneCases)
func sessionDoneMatchesPython(_ c: SessionDoneCase) {
    let got = sessionDone(
        SessionType(rawValue: c.stype),
        doneTypes: Set(c.doneTypes),
        stepOk: c.stepOk,
        longWalk: c.longWalk
    )
    #expect(got == c.expected)
}

@Test(arguments: MorningGolden.reducedCompliantCases)
func reducedCompliantMatchesPython(_ c: ReducedCompliantCase) {
    #expect(reducedCompliant(dayTypes: Set(c.dayTypes), longWalk: c.longWalk) == c.expected)
}

@Test(arguments: MorningGolden.liftFlagsCases)
func liftFlagsMatchesPython(_ c: LiftFlagsFixture) {
    let (reds, notes) = liftFlags(c.lifts)
    #expect(reds == c.reds)
    #expect(notes == c.notes)
}

/// The slope is compared on `bitPattern`, not `==`: the last operation is a
/// `pythonRound`, which preserves `-0.0`, and `0.0 == -0.0` in IEEE-754.
@Test(arguments: MorningGolden.trendKgWkCases)
func trendKgWkMatchesPython(_ c: TrendKgWkCase) throws {
    let got = try trendKgWk(c.trendRows)
    switch (got, c.expected) {
    case (nil, nil):
        break
    case (let got?, let want?):
        #expect(got.bitPattern == want.bitPattern, "got \(got), want \(want)")
    default:
        Issue.record("got \(got.map { "\($0)" } ?? "nil"), want \(c.expected.map { "\($0)" } ?? "nil")")
    }
}

@Test(arguments: MorningGolden.consecutiveDoseIndexCases)
func consecutiveDoseIndexMatchesPython(_ c: ConsecutiveDoseIndexCase) throws {
    #expect(try consecutiveDoseIndex(c.day, dosed: Set(c.dosed)) == c.expected)
}

@Test(arguments: MorningGolden.rhrCarriedOverCases)
func rhrCarriedOverMatchesPython(_ c: RhrCarriedOverCase) {
    #expect(rhrCarriedOver(c.m.vitals, today: c.today) == c.expected)
}

@Test(arguments: MorningGolden.vitalsPresentCases)
func vitalsPresentMatchesPython(_ c: VitalsPresentCase) {
    #expect(vitalsPresent(c.m.vitals) == c.expected)
}

@Test(arguments: MorningGolden.vitalsLineCases)
func vitalsLineMatchesPython(_ c: VitalsLineCase) {
    let got = vitalsLine(c.m.vitals, today: c.today)
    #expect(got == c.expected, "got \"\(got)\", want \"\(c.expected)\"")
}

@Test(arguments: MorningGolden.fmtVsCases)
func fmtVsMatchesPython(_ c: FmtVsCase) {
    let got = fmtVs(c.v, goal: c.goal, suffix: c.suffix)
    #expect(got == c.expected, "got \"\(got)\", want \"\(c.expected)\"")
}

@Test(arguments: MorningGolden.prevFromStateCases)
func prevFromStateMatchesPython(_ c: PrevFromStateCase) throws {
    #expect(try prevFromState(c.state.state, today: c.today) == c.expected.prevState)
}

@Test(arguments: MorningGolden.streakCases)
func streakMatchesPython(_ c: StreakCase) throws {
    #expect(try streak(Set(c.okDays), end: c.end) == c.expected)
}

@Test(arguments: MorningGolden.bestStreakCases)
func bestStreakMatchesPython(_ c: BestStreakCase) throws {
    #expect(try bestStreak(Set(c.okDays)) == c.expected)
}

/// The whole verdict: the string, every condition line in order, and the state
/// written back. Strings are compared with `==` — byte-exact, no normalisation.
@Test(arguments: MorningGolden.evaluateCases)
func evaluateMatchesPython(_ c: EvaluateFixture) throws {
    let got = try evaluate(
        today: c.today,
        vitals: c.vitals,
        db: c.db,
        state: c.state,
        dosedDates: c.dosedDates
    )
    #expect(got.verdict == c.verdict, "verdict: got \"\(got.verdict)\", want \"\(c.verdict)\"")
    #expect(got.conditions.count == c.conditions.count, "condition count: got \(got.conditions), want \(c.conditions)")
    for (index, want) in c.conditions.enumerated() where index < got.conditions.count {
        #expect(got.conditions[index] == want, "condition[\(index)]: got \"\(got.conditions[index])\", want \"\(want)\"")
    }
    #expect(got.newState == c.newState)
}

/// W6 card, L1 exit: no ambient clock, locale or printf-style formatting in the
/// lane's sources. `CalendarMath` (L0) is the only sanctioned date surface and
/// `formatFixed` the only sanctioned decimal formatter — a `Date()` here would
/// make the gate answer differently on a phone in another timezone.
@Test
func morningGateSourcesAvoidAmbientClockAPIs() throws {
    let sources = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()  // JIComputeTests
        .deletingLastPathComponent()  // Tests
        .deletingLastPathComponent()  // JICompute
        .appendingPathComponent("Sources/JICompute/MorningGate")
    let banned = ["Date()", "TimeZone.current", "Locale.current", "Calendar.current", "String(" + "format:"]
    let names = try FileManager.default.contentsOfDirectory(atPath: sources.path).sorted()
    #expect(!names.isEmpty, "no sources found at \(sources.path)")
    for name in names where name.hasSuffix(".swift") {
        let text = try String(contentsOf: sources.appendingPathComponent(name), encoding: .utf8)
        for needle in banned {
            #expect(!text.contains(needle), "\(name) uses \(needle)")
        }
    }
}
