import Testing
@testable import JICompute

/// Parity tests for the shared Python-semantics helpers.
///
/// Fixture is generated by `HealthTraining/scripts/parity/gen_golden_shared.py`
/// — ground truth is the Python interpreter itself. Never edit the fixture by
/// hand; run `HealthTraining/scripts/regen_goldens.py`.
///
/// 697 cases: `roundCases` 660 + `dateCases` 37. Each golden case is one test
/// case, so the count `swift test` prints IS the golden count.

// MARK: - Fixtures

struct RoundCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["v", "n", "round", "fmt"]

    let v: Double
    let n: Int
    let round: Double
    let fmt: String?

    var testDescription: String { "round(\(v), \(n))" }
}

struct DateCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["iso", "weekday", "plus40", "minus100", "diffFromEpochDate"]

    let iso: String
    let weekday: Int
    let plus40: String
    let minus100: String
    let diffFromEpochDate: Int

    var testDescription: String { iso }
}

enum SharedGolden {
    static let roundCases = GoldenLoader.require(RoundCase.self, file: "shared.golden", group: "roundCases")
    static let dateCases = GoldenLoader.require(DateCase.self, file: "shared.golden", group: "dateCases")
}

// MARK: - Tests

/// `pythonRound` and `formatFixed` against Python, exactly.
///
/// The round comparison is on `bitPattern`, not `==`: `0.0 == -0.0` is true in
/// IEEE-754, and preserving `-0.0` is a stated parity requirement
/// (`round(-0.04, 1) == -0.0` in Python). This is the `Object.is` the TS oracle
/// test uses.
///
/// `fmt` is compared with plain `==` on `String` — no normalisation.
@Test(arguments: SharedGolden.roundCases)
func pythonRoundMatchesPython(_ c: RoundCase) {
    let got = pythonRound(c.v, c.n)
    #expect(
        got.bitPattern == c.round.bitPattern,
        "round(\(c.v), \(c.n)): got \(got), want \(c.round)"
    )
    if let fmt = c.fmt, c.n >= 0 {
        let formatted = formatFixed(c.v, c.n)
        #expect(formatted == fmt, "fmt(\(c.v), \(c.n)): got \"\(formatted)\", want \"\(fmt)\"")
    }
}

/// `CalendarMath` against Python `datetime.date`.
@Test(arguments: SharedGolden.dateCases)
func calendarMathMatchesPython(_ c: DateCase) throws {
    #expect(try CalendarMath.isoWeekday(c.iso) == c.weekday)
    #expect(try CalendarMath.addDays(c.iso, 40) == c.plus40)
    #expect(try CalendarMath.addDays(c.iso, -100) == c.minus100)
    #expect(try CalendarMath.diffDays(c.iso, "2026-01-01") == c.diffFromEpochDate)
}
