import Testing
@testable import JICompute

/// Parity tests for the sleep-quality port (`Sources/JICompute/SleepScore/*`).
///
/// Fixture is generated by `HealthTraining/scripts/parity/gen_golden_sleep.py`
/// — ground truth is the live `app/vitals/{sleep_score,bedtime,sleep_debt}.py`.
/// Never edit the fixture by hand; run `HealthTraining/scripts/regen_goldens.py`.
///
/// 432 cases in one flat `cases` array, discriminated by `fn`:
/// `computeSleepScore` 184 · `bedtimeConsistencySdMin` 96 ·
/// `derivePersonalBaselineHours` 77 · `computeSleepDebtSeries` 75. Each golden
/// case is one test case, so the count `swift test` prints IS the golden count;
/// `sleepGoldenCaseCountIsComplete` pins the per-`fn` split so a fixture that
/// loses a group cannot pass by simply running fewer cases.
///
/// Every `Double` comparison is on `bitPattern`, not `==`: `0.0 == -0.0` is true
/// in IEEE-754 and the fixture contains a `-0.0`, so `==` would let a sign flip
/// through. This is the `Object.is` the TS oracle test uses.

// MARK: - Fixture decoding

private struct StrictKeyError: Error, CustomStringConvertible {
    let context: String
    let keys: [String]
    var description: String {
        "sleep.golden \(context) has unknown key(s) \(keys.sorted().joined(separator: ", ")) — the Swift port is behind the generator"
    }
}

private struct UnknownFnError: Error, CustomStringConvertible {
    let fn: String
    var description: String { "sleep.golden has unknown fn \"\(fn)\" — the Swift port is behind the generator" }
}

/// Fails on any JSON key the decoding type does not claim. `GoldenLoader`'s
/// `StrictCase` only guards the top level, so nested objects re-do the check.
private func requireKeys(_ decoder: Decoder, _ allowed: Set<String>, _ context: String) throws {
    let raw = try decoder.container(keyedBy: AnyKey.self)
    let unknown = Set(raw.allKeys.map(\.stringValue)).subtracting(allowed)
    guard unknown.isEmpty else { throw StrictKeyError(context: context, keys: Array(unknown)) }
}

struct SleepScoreCase: Sendable, CustomTestStringConvertible {
    let durationSec: Int?
    let deepSec: Int?
    let remSec: Int?
    let awakeSec: Int?
    let expected: Int?

    var testDescription: String {
        "computeSleepScore(\(durationSec.map(String.init) ?? "nil"), \(deepSec.map(String.init) ?? "nil"), \(remSec.map(String.init) ?? "nil"), \(awakeSec.map(String.init) ?? "nil"))"
    }
}

struct BedtimeCase: Sendable, CustomTestStringConvertible {
    let onsetTimes: [String?]
    let expected: Double?

    var testDescription: String { "bedtimeConsistencySdMin(n=\(onsetTimes.count), present=\(onsetTimes.compactMap { $0 }.count))" }
}

struct BaselineCase: Sendable, CustomTestStringConvertible {
    let durationHours: [Double]
    let minNights: Int
    let expected: Double?

    var testDescription: String { "derivePersonalBaselineHours(n=\(durationHours.count), minNights=\(minNights))" }
}

struct SleepDebtCase: Sendable, CustomTestStringConvertible {
    let nights: [NightlySleep]
    let baselineHours: Double
    let windowDays: Int
    let expected: [SleepDebtDay]

    var testDescription: String { "computeSleepDebtSeries(n=\(nights.count), baseline=\(baselineHours), window=\(windowDays))" }
}

/// One entry of the flat `cases` array, decoded per its `fn` discriminator.
struct SleepCase: GoldenCase, CustomTestStringConvertible {
    static let allowedKeys: Set<String> = ["fn", "input", "output"]

    enum Payload: Sendable {
        case score(SleepScoreCase)
        case bedtime(BedtimeCase)
        case baseline(BaselineCase)
        case debt(SleepDebtCase)
    }

    let fn: String
    let payload: Payload

    var testDescription: String {
        switch payload {
        case .score(let c): c.testDescription
        case .bedtime(let c): c.testDescription
        case .baseline(let c): c.testDescription
        case .debt(let c): c.testDescription
        }
    }

    private struct ScoreInput: Decodable {
        let durationSec: Int?
        let deepSec: Int?
        let remSec: Int?
        let awakeSec: Int?

        init(from decoder: Decoder) throws {
            try requireKeys(decoder, ["durationSec", "deepSec", "remSec", "awakeSec"], "computeSleepScore input")
            let c = try decoder.container(keyedBy: AnyKey.self)
            durationSec = try c.decodeIfPresent(Int.self, forKey: AnyKey("durationSec"))
            deepSec = try c.decodeIfPresent(Int.self, forKey: AnyKey("deepSec"))
            remSec = try c.decodeIfPresent(Int.self, forKey: AnyKey("remSec"))
            awakeSec = try c.decodeIfPresent(Int.self, forKey: AnyKey("awakeSec"))
        }
    }

    private struct BedtimeInput: Decodable {
        let onsetTimes: [String?]

        init(from decoder: Decoder) throws {
            try requireKeys(decoder, ["onsetTimes"], "bedtimeConsistencySdMin input")
            let c = try decoder.container(keyedBy: AnyKey.self)
            onsetTimes = try c.decode([String?].self, forKey: AnyKey("onsetTimes"))
        }
    }

    private struct BaselineInput: Decodable {
        let durationHours: [Double]
        let minNights: Int

        init(from decoder: Decoder) throws {
            try requireKeys(decoder, ["durationHours", "minNights"], "derivePersonalBaselineHours input")
            let c = try decoder.container(keyedBy: AnyKey.self)
            durationHours = try c.decode([Double].self, forKey: AnyKey("durationHours"))
            minNights = try c.decode(Int.self, forKey: AnyKey("minNights"))
        }
    }

    private struct NightInput: Decodable {
        let night: NightlySleep

        init(from decoder: Decoder) throws {
            try requireKeys(decoder, ["date", "duration_hours"], "computeSleepDebtSeries nights[]")
            let c = try decoder.container(keyedBy: AnyKey.self)
            night = NightlySleep(
                date: try c.decode(String.self, forKey: AnyKey("date")),
                durationHours: try c.decode(Double.self, forKey: AnyKey("duration_hours"))
            )
        }
    }

    private struct DebtInput: Decodable {
        let nights: [NightInput]
        let baselineHours: Double
        let windowDays: Int

        init(from decoder: Decoder) throws {
            try requireKeys(decoder, ["nights", "baselineHours", "windowDays"], "computeSleepDebtSeries input")
            let c = try decoder.container(keyedBy: AnyKey.self)
            nights = try c.decode([NightInput].self, forKey: AnyKey("nights"))
            baselineHours = try c.decode(Double.self, forKey: AnyKey("baselineHours"))
            windowDays = try c.decode(Int.self, forKey: AnyKey("windowDays"))
        }
    }

    private struct DebtDayOutput: Decodable {
        let day: SleepDebtDay

        init(from decoder: Decoder) throws {
            try requireKeys(
                decoder,
                ["date", "duration_hours", "baseline_hours", "debt_hours", "nights_in_window"],
                "computeSleepDebtSeries output[]"
            )
            let c = try decoder.container(keyedBy: AnyKey.self)
            day = SleepDebtDay(
                date: try c.decode(String.self, forKey: AnyKey("date")),
                durationHours: try c.decode(Double.self, forKey: AnyKey("duration_hours")),
                baselineHours: try c.decode(Double.self, forKey: AnyKey("baseline_hours")),
                debtHours: try c.decode(Double.self, forKey: AnyKey("debt_hours")),
                nightsInWindow: try c.decode(Int.self, forKey: AnyKey("nights_in_window"))
            )
        }
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: AnyKey.self)
        let fn = try c.decode(String.self, forKey: AnyKey("fn"))
        self.fn = fn
        switch fn {
        case "computeSleepScore":
            let input = try c.decode(ScoreInput.self, forKey: AnyKey("input"))
            payload = .score(SleepScoreCase(
                durationSec: input.durationSec,
                deepSec: input.deepSec,
                remSec: input.remSec,
                awakeSec: input.awakeSec,
                expected: try c.decodeIfPresent(Int.self, forKey: AnyKey("output"))
            ))
        case "bedtimeConsistencySdMin":
            let input = try c.decode(BedtimeInput.self, forKey: AnyKey("input"))
            payload = .bedtime(BedtimeCase(
                onsetTimes: input.onsetTimes,
                expected: try c.decodeIfPresent(Double.self, forKey: AnyKey("output"))
            ))
        case "derivePersonalBaselineHours":
            let input = try c.decode(BaselineInput.self, forKey: AnyKey("input"))
            payload = .baseline(BaselineCase(
                durationHours: input.durationHours,
                minNights: input.minNights,
                expected: try c.decodeIfPresent(Double.self, forKey: AnyKey("output"))
            ))
        case "computeSleepDebtSeries":
            let input = try c.decode(DebtInput.self, forKey: AnyKey("input"))
            payload = .debt(SleepDebtCase(
                nights: input.nights.map(\.night),
                baselineHours: input.baselineHours,
                windowDays: input.windowDays,
                expected: try c.decode([DebtDayOutput].self, forKey: AnyKey("output")).map(\.day)
            ))
        default:
            throw UnknownFnError(fn: fn)
        }
    }
}

enum SleepGolden {
    static let all = GoldenLoader.require(SleepCase.self, file: "sleep.golden", group: "cases")

    static let scoreCases: [SleepScoreCase] = all.compactMap {
        if case .score(let c) = $0.payload { return c } else { return nil }
    }
    static let bedtimeCases: [BedtimeCase] = all.compactMap {
        if case .bedtime(let c) = $0.payload { return c } else { return nil }
    }
    static let baselineCases: [BaselineCase] = all.compactMap {
        if case .baseline(let c) = $0.payload { return c } else { return nil }
    }
    static let debtCases: [SleepDebtCase] = all.compactMap {
        if case .debt(let c) = $0.payload { return c } else { return nil }
    }
}

// MARK: - Tests

/// The fixture split, pinned: a group that silently vanished would otherwise
/// just run fewer parametrised cases and still report green.
@Test
func sleepGoldenCaseCountIsComplete() {
    #expect(SleepGolden.all.count == 432)
    #expect(SleepGolden.scoreCases.count == 184)
    #expect(SleepGolden.bedtimeCases.count == 96)
    #expect(SleepGolden.baselineCases.count == 77)
    #expect(SleepGolden.debtCases.count == 75)
}

@Test(arguments: SleepGolden.scoreCases)
func computeSleepScoreMatchesPython(_ c: SleepScoreCase) {
    let got = computeSleepScore(durationSec: c.durationSec, deepSec: c.deepSec, remSec: c.remSec, awakeSec: c.awakeSec)
    #expect(got == c.expected, "\(c.testDescription): got \(String(describing: got)), want \(String(describing: c.expected))")
}

@Test(arguments: SleepGolden.bedtimeCases)
func bedtimeConsistencySdMinMatchesPython(_ c: BedtimeCase) throws {
    let got = try bedtimeConsistencySdMin(c.onsetTimes)
    expectSameDouble(got, c.expected, c.testDescription)
}

@Test(arguments: SleepGolden.baselineCases)
func derivePersonalBaselineHoursMatchesPython(_ c: BaselineCase) {
    let got = derivePersonalBaselineHours(c.durationHours, minNights: c.minNights)
    expectSameDouble(got, c.expected, c.testDescription)
}

@Test(arguments: SleepGolden.debtCases)
func computeSleepDebtSeriesMatchesPython(_ c: SleepDebtCase) throws {
    let got = try computeSleepDebtSeries(c.nights, baselineHours: c.baselineHours, windowDays: c.windowDays)
    #expect(got.count == c.expected.count, "\(c.testDescription): series length")
    for (i, (g, w)) in zip(got, c.expected).enumerated() {
        #expect(g.date == w.date, "\(c.testDescription)[\(i)].date")
        #expect(g.nightsInWindow == w.nightsInWindow, "\(c.testDescription)[\(i)].nightsInWindow")
        expectSameDouble(g.durationHours, w.durationHours, "\(c.testDescription)[\(i)].durationHours")
        expectSameDouble(g.baselineHours, w.baselineHours, "\(c.testDescription)[\(i)].baselineHours")
        expectSameDouble(g.debtHours, w.debtHours, "\(c.testDescription)[\(i)].debtHours")
    }
}

/// Bit-exact `Double?` comparison — `-0.0` must not pass as `0.0`.
private func expectSameDouble(
    _ got: Double?,
    _ want: Double?,
    _ label: String,
    sourceLocation: SourceLocation = #_sourceLocation
) {
    #expect(
        got?.bitPattern == want?.bitPattern,
        "\(label): got \(String(describing: got)), want \(String(describing: want))",
        sourceLocation: sourceLocation
    )
}
